# Numpy调用函数运算

In [1]:
import numpy as np
stock_change = np.random.normal(0, 1, size=(5, 5))
stock_change

array([[ 1.54557409, -0.6678381 ,  0.54112615,  0.56934079, -2.05360222],
       [-0.95766407,  0.03122786, -0.50502505, -1.02471915, -3.64643962],
       [ 0.90435795,  0.23931019, -0.00878454,  1.67170784,  0.38939874],
       [ 1.29490188, -0.3868329 ,  0.41326687, -0.59602734,  0.39547755],
       [-1.35311038,  0.79737029,  0.35239454,  1.66784047,  0.23197086]])

## 逻辑运算

In [5]:
# 判断stock_change中的每一个元素是否都大于0.5，用true和false返回
# 列表不支持这样的操作list!!!!
stock_change > 0.5

array([[False,  True,  True,  True, False],
       [ True, False, False, False, False],
       [False,  True, False,  True, False],
       [False, False,  True, False, False],
       [ True, False, False, False, False]])

In [7]:
# 将大于1的元素赋值为2
stock_change[stock_change > 1] = 2
stock_change

array([[ 0.18493722,  2.        ,  0.83100155,  2.        ,  0.22384062],
       [ 2.        ,  0.19699784, -0.34030608, -1.22006366, -0.60633654],
       [ 0.08280692,  2.        , -0.22979622,  2.        , -0.33257673],
       [-0.23197117,  0.17861629,  2.        , -0.27979931, -0.73833876],
       [ 0.50857217, -1.30012232, -0.79107691, -0.31384127, -1.21434927]])

## 通用判断函数

In [10]:
# 判断stock_change里面所有的元素是否是大于2的
np.all(stock_change > 2)

False

In [11]:
# 判断stock_change里面是否存在一个元素是大于2的
np.any(stock_change > 1)

True

## 三元运算符(np.where)

In [14]:
# 将stock_change中的元素大于0的赋值为1， 否则为0（但不返回新值）
np.where(stock_change > 0, 1, 0)

array([[1, 1, 1, 1, 1],
       [1, 1, 0, 0, 0],
       [1, 1, 0, 1, 0],
       [0, 1, 1, 0, 0],
       [1, 0, 0, 0, 0]])

In [15]:
# 将stock_change中的元素大于0且小于1.5的赋值为1， 否则为0（但不返回新值）
np.where(np.logical_and(stock_change > 0, stock_change < 1.5), 1, 0)

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0]])

In [16]:
# 将stock_change中的元素大于0或者小于-0.5的赋值为1， 否则为0（但不返回新值）
np.where(np.logical_or(stock_change > 0, stock_change < -0.5), 1, 0)

array([[1, 1, 1, 1, 1],
       [1, 1, 0, 1, 1],
       [1, 1, 0, 1, 0],
       [0, 1, 1, 0, 1],
       [1, 1, 1, 0, 1]])

## 统计指标

In [21]:
stock = np.random.normal(15, 1, size=(6, 6))
print(stock)

[[14.64530327 15.46863366 15.7880149  14.84166538 14.6539198  14.64758643]
 [12.53531023 15.80552082 13.39694149 15.36156256 14.19782563 16.34720623]
 [13.78177245 15.62767558 13.66533166 14.7345886  15.00028239 15.42935938]
 [12.33224173 15.00877056 15.04455334 17.05780442 13.73283615 15.4380149 ]
 [15.53470059 13.9293949  14.47032749 15.98390205 13.96452448 13.79599957]
 [14.45872098 15.60375088 15.6266369  15.44960259 13.77558159 14.591284  ]]


In [27]:
# 最大值,axis=1表示按照行
print(np.max(stock, axis=1))
print(np.max(stock, axis=0))
print(stock.max(axis=0))

[15.7880149  16.34720623 15.62767558 17.05780442 15.98390205 15.6266369 ]
[15.53470059 15.80552082 15.7880149  17.05780442 15.00028239 16.34720623]
[15.53470059 15.80552082 15.7880149  17.05780442 15.00028239 16.34720623]


In [28]:
# 最小值,axis=1表示按照行
print(np.min(stock, axis=1))
print(np.min(stock, axis=0))
print(stock.min(axis=0))

[14.64530327 12.53531023 13.66533166 12.33224173 13.79599957 13.77558159]
[12.33224173 13.9293949  13.39694149 14.7345886  13.73283615 13.79599957]
[12.33224173 13.9293949  13.39694149 14.7345886  13.73283615 13.79599957]


In [32]:
# 中位数,axis=1表示按照行
print(np.median(stock, axis=1))
print(np.median(stock, axis=0))
# print(stock.median(axis=0)) 错误的！！！！

[14.74779259 14.77969409 14.86743549 15.02666195 14.21742598 15.0204433 ]
[14.12024671 15.53619227 14.75744041 15.40558257 14.08117505 15.0384729 ]
[1.3120042  0.40430744 0.82919579 0.61186471 0.21628644 0.65361022]


In [30]:
# 均值,axis=1表示按照行
print(np.mean(stock, axis=1))
print(np.mean(stock, axis=0))
print(stock.mean(axis=0))

[15.00752057 14.60739449 14.70650168 14.76903685 14.61314151 14.91759616]
[13.88134154 15.2406244  14.66530096 15.57152093 14.22082834 15.04157509]
[13.88134154 15.2406244  14.66530096 15.57152093 14.22082834 15.04157509]


In [35]:
# 标准差,axis=1表示按照行
print(np.std(stock, axis=1))
print(np.std(stock, axis=0))
print(stock.std(axis=0))

[0.4537055  1.35140034 0.7524781  1.4623641  0.84701297 0.69255821]
[1.14542752 0.63585175 0.91060188 0.78221781 0.46506606 0.80846164]
[1.14542752 0.63585175 0.91060188 0.78221781 0.46506606 0.80846164]


In [33]:
# 方差,axis=1表示按照行
print(np.var(stock, axis=1))
print(np.var(stock, axis=0))
print(stock.var(axis=0))

[0.20584868 1.82628289 0.56622329 2.13850876 0.71743098 0.47963688]
[1.3120042  0.40430744 0.82919579 0.61186471 0.21628644 0.65361022]
[1.3120042  0.40430744 0.82919579 0.61186471 0.21628644 0.65361022]


### 定位最大或者最小

In [39]:
print(stock)
# 找出stock中最大的那个数，第一次出现的位置，最小用argmin，效果同理
stock.argmax()

[[14.64530327 15.46863366 15.7880149  14.84166538 14.6539198  14.64758643]
 [12.53531023 15.80552082 13.39694149 15.36156256 14.19782563 16.34720623]
 [13.78177245 15.62767558 13.66533166 14.7345886  15.00028239 15.42935938]
 [12.33224173 15.00877056 15.04455334 17.05780442 13.73283615 15.4380149 ]
 [15.53470059 13.9293949  14.47032749 15.98390205 13.96452448 13.79599957]
 [14.45872098 15.60375088 15.6266369  15.44960259 13.77558159 14.591284  ]]


21

In [40]:
# 按照行定位max元素
stock.argmax(axis=1)

array([2, 5, 1, 3, 3, 2])

# Numpy数组运算符计算

In [7]:
arr1 = np.array([[1, 2, 3, 4], [2, 3, 4, 5]])
arr2 = np.array([[11, 21, 31, 41], [22, 32, 42, 52]])
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [3]:
arr1 + 1

array([[2, 3, 4, 5],
       [3, 4, 5, 6]])

In [4]:
arr1 / 2

array([[0.5, 1. , 1.5, 2. ],
       [1. , 1.5, 2. , 2.5]])

In [5]:
l = [1, 2, 3]
l * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [8]:
# 对应元素相加
arr1 + arr2

array([[12, 23, 34, 45],
       [24, 35, 46, 57]])

## 广播机制(下列条件满足一个即可运算)
* 维度相等
* shape(其中相对应的地方有一个为1) 

In [13]:
# A  (4d array): 9 x 1 x 7 x 1
# B  (3d array):     8 x 1 x 5
# result(4d array): 9 x 8 x 7 x 5

In [12]:
print(arr1.shape)             # shape:(2, 4)
arr3 = np.array([1, 2, 3, 4]) # shape:(1, 4)

(2, 4)


In [14]:
arr1 + arr3 # arr1的每一行都加上arr3

array([[2, 4, 6, 8],
       [3, 5, 7, 9]])

## 数组矩阵乘法
* np.matmul
* np.dot

In [16]:
Matrix_1 = np.array([[2, 1, 1],
                     [3, 2, 1]]) # shape:(2, 3)
Matrix_2 = np.array([[2, 1],
                     [3, 2],
                     [1, 4]]) #shape:(3, 2)

In [17]:
# matmul不支持矩阵和数字的相乘
np.matmul(Matrix_1, Matrix_2)

array([[ 8,  8],
       [13, 11]])

In [18]:
np.dot(Matrix_1, Matrix_2)

array([[ 8,  8],
       [13, 11]])

In [19]:
np.dot(Matrix_1, 10)

array([[20, 10, 10],
       [30, 20, 10]])