## Example1:随机生成8支股票在10个工作日的涨幅
* 假设涨幅是服从标准正态分布的随机数
* 使用Numpy创建

In [2]:
import numpy as np

In [2]:
stock_change = np.random.normal(0, 1, size=(4, 5))
stock_change

array([[-1.11621094, -0.21354023,  0.5581646 , -1.54092561, -1.13284461],
       [ 1.059868  ,  1.10259765,  0.76896185, -0.77727606, -0.90900192],
       [-0.97338003,  0.68558485, -1.38874641,  0.78860752, -1.86835345],
       [ 0.69868705, -0.50903825, -0.27836606,  0.48225089,  0.00665251]])

## 数组的索引 & 切片

In [16]:
# 显示前两行 前三列
print(stock_change[0:2, 0:3])
print('')
print(stock_change[0, 0:3])

[[-0.34870071  1.18882118  0.85403344]
 [ 0.92003491  0.63527317 -0.86840077]]

[-0.34870071  1.18882118  0.85403344]


### 多维数组的索引 & 切片

In [17]:
a3 = np.array([[[1, 2, 3], 
                [4, 5, 6]],
               
              [[7, 8, 9],
              [10, 11, 12]]
              ])
# a3.shape = (2, 2, 3)
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [12]:
a3[1, 1, 2]

12

## 形状修改

In [18]:
# reshape是先将所有数据排成一行，然后再更改形状
stock_change.reshape((5, 4))

array([[-0.34870071,  1.18882118,  0.85403344, -0.96648594],
       [-0.57264086,  0.92003491,  0.63527317, -0.86840077],
       [-1.82573194,  0.15936867,  1.45164859,  0.89743458],
       [ 0.2448957 , -2.81929414,  0.00845409,  0.11095666],
       [-0.75968421, -2.81197907, -1.27913722,  0.85384879]])

In [19]:
# -1表示然系统自己计算（真正应该是10行2列）
stock_change.reshape((-1, 2))

array([[-0.34870071,  1.18882118],
       [ 0.85403344, -0.96648594],
       [-0.57264086,  0.92003491],
       [ 0.63527317, -0.86840077],
       [-1.82573194,  0.15936867],
       [ 1.45164859,  0.89743458],
       [ 0.2448957 , -2.81929414],
       [ 0.00845409,  0.11095666],
       [-0.75968421, -2.81197907],
       [-1.27913722,  0.85384879]])

In [21]:
# resize会在原来的基础上会进行更改，而reshape不变
stock_change.resize((10, 2))
stock_change

array([[-0.34870071,  1.18882118],
       [ 0.85403344, -0.96648594],
       [-0.57264086,  0.92003491],
       [ 0.63527317, -0.86840077],
       [-1.82573194,  0.15936867],
       [ 1.45164859,  0.89743458],
       [ 0.2448957 , -2.81929414],
       [ 0.00845409,  0.11095666],
       [-0.75968421, -2.81197907],
       [-1.27913722,  0.85384879]])

In [22]:
# 转置(也是不会产生新的变量)
stock_change.T

array([[-0.34870071,  0.85403344, -0.57264086,  0.63527317, -1.82573194,
         1.45164859,  0.2448957 ,  0.00845409, -0.75968421, -1.27913722],
       [ 1.18882118, -0.96648594,  0.92003491, -0.86840077,  0.15936867,
         0.89743458, -2.81929414,  0.11095666, -2.81197907,  0.85384879]])

## 类型修改

In [3]:
stock_change

array([[-1.11621094, -0.21354023,  0.5581646 , -1.54092561, -1.13284461],
       [ 1.059868  ,  1.10259765,  0.76896185, -0.77727606, -0.90900192],
       [-0.97338003,  0.68558485, -1.38874641,  0.78860752, -1.86835345],
       [ 0.69868705, -0.50903825, -0.27836606,  0.48225089,  0.00665251]])

In [7]:
# 修改成np.int32类型，但不产生新类型
print(stock_change.astype(np.int32))
stock_change

[[-1  0  0 -1 -1]
 [ 1  1  0  0  0]
 [ 0  0 -1  0 -1]
 [ 0  0  0  0  0]]


array([[-1.11621094, -0.21354023,  0.5581646 , -1.54092561, -1.13284461],
       [ 1.059868  ,  1.10259765,  0.76896185, -0.77727606, -0.90900192],
       [-0.97338003,  0.68558485, -1.38874641,  0.78860752, -1.86835345],
       [ 0.69868705, -0.50903825, -0.27836606,  0.48225089,  0.00665251]])

In [9]:
# 转换为字符串形式
arr = np.array([[1, 2],
               [2, 3]])
arr.tostring()

/var/folders/g3/jwwz_y8d6wn55b900n__7cyw0000gn/T/ipykernel_5171/601192065.py:3: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  arr.tostring()


b'\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00'

## 数组的去重

In [10]:
temp = np.array([[1, 2, 3, 4], [2, 3, 5, 6]])

In [11]:
# 去掉重复值，不产生新的返回值
np.unique(temp)

array([1, 2, 3, 4, 5, 6])

In [12]:
temp

array([[1, 2, 3, 4],
       [2, 3, 5, 6]])

## 数组堆叠与合并
数组堆叠是指沿特定的方向把多个数组合并到一起。
* hstack()：水平堆叠
* vstack()：垂直堆叠
* concatenate():其中axis=0指垂直堆叠，axis=1指水平堆叠

In [6]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [4]:
# 水平堆叠
np.hstack((arr1, arr2))

matrix([[1, 2, 3, 4, 5, 6]])

In [5]:
# 垂直堆叠
np.vstack((arr1, arr2))

matrix([[1, 2, 3],
        [4, 5, 6]])

In [10]:
arr3 = np.matrix([[1], 
                 [2],
                 [3]])
arr4 = np.matrix([[4],
                 [5],
                 [6]])

In [11]:
np.hstack((arr3, arr4))

matrix([[1, 4],
        [2, 5],
        [3, 6]])

In [12]:
np.vstack((arr3, arr4))

matrix([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [13]:
np.concatenate((arr3, arr4))

matrix([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [14]:
np.concatenate((arr3, arr4), axis=1)

matrix([[1, 4],
        [2, 5],
        [3, 6]])

In [8]:
arr3

matrix([[1],
        [2],
        [3]])

(3, 1)